/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as OgIndexRouteImport } from './routes/og.index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as LocaleHeaderLayoutRouteImport } from './routes/$locale._header-layout'
import { Route as ApiAdminHeroCandidateImageRouteImport } from './routes/api.admin.hero-candidate-image'
import { Route as LocaleHeaderLayoutSearchRouteImport } from './routes/$locale._header-layout.search'
import { Route as LocaleHeaderLayoutNotificationsRouteImport } from './routes/$locale._header-layout.notifications'
import { Route as LocaleHeaderLayoutHomeRouteImport } from './routes/$locale._header-layout.home'
import { Route as LocaleHeaderLayoutAboutRouteImport } from './routes/$locale._header-layout.about'
import { Route as LocaleHeaderLayoutAdminLayoutRouteImport } from './routes/$locale._header-layout._admin-layout'
import { Route as ApiAuthAtprotoSignupRouteImport } from './routes/api.auth.atproto.signup'
import { Route as ApiAuthAtprotoMetadataDotjsonRouteImport } from './routes/api.auth.atproto.metadata[.]json'
import { Route as ApiAuthAtprotoJwksDotjsonRouteImport } from './routes/api.auth.atproto.jwks[.]json'
import { Route as ApiAuthAtprotoCallbackRouteImport } from './routes/api.auth.atproto.callback'
import { Route as ApiAuthAtprotoAuthorizeRouteImport } from './routes/api.auth.atproto.authorize'
import { Route as LocaleHeaderLayoutProtocolTagsRouteImport } from './routes/$locale._header-layout.protocol.tags'
import { Route as LocaleHeaderLayoutProtocolListingsRouteImport } from './routes/$locale._header-layout.protocol.listings'
import { Route as LocaleHeaderLayoutProtocolCategoryRouteImport } from './routes/$locale._header-layout.protocol.$category'
import { Route as LocaleHeaderLayoutProfileActorRouteImport } from './routes/$locale._header-layout.profile.$actor'
import { Route as LocaleHeaderLayoutProductsCreateRouteImport } from './routes/$locale._header-layout.products.create'
import { Route as LocaleHeaderLayoutProductClaimRouteImport } from './routes/$locale._header-layout.product.claim'
import { Route as LocaleHeaderLayoutDevCategoriesRouteImport } from './routes/$locale._header-layout.dev.categories'
import { Route as LocaleHeaderLayoutDevAppTagsRouteImport } from './routes/$locale._header-layout.dev.app-tags'
import { Route as LocaleHeaderLayoutCategoriesCategoryIdRouteImport } from './routes/$locale._header-layout.categories.$categoryId'
import { Route as LocaleHeaderLayoutAppsTagsRouteImport } from './routes/$locale._header-layout.apps.tags'
import { Route as LocaleHeaderLayoutAppsAllRouteImport } from './routes/$locale._header-layout.apps.all'
import { Route as LocaleHeaderLayoutAppsTagRouteImport } from './routes/$locale._header-layout.apps.$tag'
import { Route as LocaleHeaderLayoutProductsProductIdIndexRouteImport } from './routes/$locale._header-layout.products.$productId.index'
import { Route as LocaleHeaderLayoutEcosystemsAppIndexRouteImport } from './routes/$locale._header-layout.ecosystems.$app.index'
import { Route as LocaleHeaderLayoutAdminLayoutAdminIndexRouteImport } from './routes/$locale._header-layout._admin-layout.admin.index'
import { Route as LocaleHeaderLayoutProductsProductIdReviewsRouteImport } from './routes/$locale._header-layout.products.$productId.reviews'
import { Route as LocaleHeaderLayoutProductsProductIdMentionsRouteImport } from './routes/$locale._header-layout.products.$productId.mentions'
import { Route as LocaleHeaderLayoutProductsProductIdEditRouteImport } from './routes/$locale._header-layout.products.$productId.edit'
import { Route as LocaleHeaderLayoutEcosystemsAppAllRouteImport } from './routes/$locale._header-layout.ecosystems.$app.all'
import { Route as LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport } from './routes/$locale._header-layout._admin-layout.admin.unverified-listings'
import { Route as LocaleHeaderLayoutAdminLayoutAdminReviewsRouteImport } from './routes/$locale._header-layout._admin-layout.admin.reviews'
import { Route as LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRouteImport } from './routes/$locale._header-layout._admin-layout.admin.recently-claimed'
import { Route as LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRouteImport } from './routes/$locale._header-layout._admin-layout.admin.pending-claims'
import { Route as LocaleHeaderLayoutAdminLayoutAdminManagedListingsRouteImport } from './routes/$locale._header-layout._admin-layout.admin.managed-listings'
import { Route as LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRouteImport } from './routes/$locale._header-layout._admin-layout.admin.listing-product-accounts'
import { Route as LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRouteImport } from './routes/$locale._header-layout._admin-layout.admin.home-page-hero'
import { Route as LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRouteImport } from './routes/$locale._header-layout._admin-layout.admin.hero-candidates'
import { Route as LocaleHeaderLayoutAdminLayoutAdminHeroArtRouteImport } from './routes/$locale._header-layout._admin-layout.admin.hero-art'
import { Route as LocaleHeaderLayoutAdminLayoutAdminAdminsRouteImport } from './routes/$locale._header-layout._admin-layout.admin.admins'
import { Route as LocaleHeaderLayoutAdminLayoutAdminAddListingRouteImport } from './routes/$locale._header-layout._admin-layout.admin.add-listing'
import { Route as LocaleHeaderLayoutProductsProductIdReviewsIndexRouteImport } from './routes/$locale._header-layout.products.$productId.reviews.index'
import { Route as LocaleHeaderLayoutProductsProductIdReviewsWriteRouteImport } from './routes/$locale._header-layout.products.$productId.reviews.write'
import { Route as LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport } from './routes/$locale._header-layout.products.$productId.reviews.$reviewId.edit'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const OgIndexRoute = OgIndexRouteImport.update({
  id: '/og/',
  path: '/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleHeaderLayoutRoute = LocaleHeaderLayoutRouteImport.update({
  id: '/_header-layout',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiAdminHeroCandidateImageRoute =
  ApiAdminHeroCandidateImageRouteImport.update({
    id: '/api/admin/hero-candidate-image',
    path: '/api/admin/hero-candidate-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleHeaderLayoutSearchRoute =
  LocaleHeaderLayoutSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutNotificationsRoute =
  LocaleHeaderLayoutNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutHomeRoute = LocaleHeaderLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LocaleHeaderLayoutRoute,
} as any)
const LocaleHeaderLayoutAboutRoute = LocaleHeaderLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleHeaderLayoutRoute,
} as any)
const LocaleHeaderLayoutAdminLayoutRoute =
  LocaleHeaderLayoutAdminLayoutRouteImport.update({
    id: '/_admin-layout',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const ApiAuthAtprotoSignupRoute = ApiAuthAtprotoSignupRouteImport.update({
  id: '/api/auth/atproto/signup',
  path: '/api/auth/atproto/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoMetadataDotjsonRoute =
  ApiAuthAtprotoMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/metadata.json',
    path: '/api/auth/atproto/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoJwksDotjsonRoute =
  ApiAuthAtprotoJwksDotjsonRouteImport.update({
    id: '/api/auth/atproto/jwks.json',
    path: '/api/auth/atproto/jwks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoCallbackRoute = ApiAuthAtprotoCallbackRouteImport.update({
  id: '/api/auth/atproto/callback',
  path: '/api/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoAuthorizeRoute = ApiAuthAtprotoAuthorizeRouteImport.update({
  id: '/api/auth/atproto/authorize',
  path: '/api/auth/atproto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleHeaderLayoutProtocolTagsRoute =
  LocaleHeaderLayoutProtocolTagsRouteImport.update({
    id: '/protocol/tags',
    path: '/protocol/tags',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutProtocolListingsRoute =
  LocaleHeaderLayoutProtocolListingsRouteImport.update({
    id: '/protocol/listings',
    path: '/protocol/listings',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutProtocolCategoryRoute =
  LocaleHeaderLayoutProtocolCategoryRouteImport.update({
    id: '/protocol/$category',
    path: '/protocol/$category',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutProfileActorRoute =
  LocaleHeaderLayoutProfileActorRouteImport.update({
    id: '/profile/$actor',
    path: '/profile/$actor',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutProductsCreateRoute =
  LocaleHeaderLayoutProductsCreateRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutProductClaimRoute =
  LocaleHeaderLayoutProductClaimRouteImport.update({
    id: '/product/claim',
    path: '/product/claim',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutDevCategoriesRoute =
  LocaleHeaderLayoutDevCategoriesRouteImport.update({
    id: '/dev/categories',
    path: '/dev/categories',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutDevAppTagsRoute =
  LocaleHeaderLayoutDevAppTagsRouteImport.update({
    id: '/dev/app-tags',
    path: '/dev/app-tags',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutCategoriesCategoryIdRoute =
  LocaleHeaderLayoutCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutAppsTagsRoute =
  LocaleHeaderLayoutAppsTagsRouteImport.update({
    id: '/apps/tags',
    path: '/apps/tags',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutAppsAllRoute =
  LocaleHeaderLayoutAppsAllRouteImport.update({
    id: '/apps/all',
    path: '/apps/all',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutAppsTagRoute =
  LocaleHeaderLayoutAppsTagRouteImport.update({
    id: '/apps/$tag',
    path: '/apps/$tag',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutProductsProductIdIndexRoute =
  LocaleHeaderLayoutProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutEcosystemsAppIndexRoute =
  LocaleHeaderLayoutEcosystemsAppIndexRouteImport.update({
    id: '/ecosystems/$app/',
    path: '/ecosystems/$app/',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminIndexRoute =
  LocaleHeaderLayoutAdminLayoutAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutProductsProductIdReviewsRoute =
  LocaleHeaderLayoutProductsProductIdReviewsRouteImport.update({
    id: '/products/$productId/reviews',
    path: '/products/$productId/reviews',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutProductsProductIdMentionsRoute =
  LocaleHeaderLayoutProductsProductIdMentionsRouteImport.update({
    id: '/products/$productId/mentions',
    path: '/products/$productId/mentions',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutProductsProductIdEditRoute =
  LocaleHeaderLayoutProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutEcosystemsAppAllRoute =
  LocaleHeaderLayoutEcosystemsAppAllRouteImport.update({
    id: '/ecosystems/$app/all',
    path: '/ecosystems/$app/all',
    getParentRoute: () => LocaleHeaderLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRoute =
  LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport.update({
    id: '/admin/unverified-listings',
    path: '/admin/unverified-listings',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminReviewsRoute =
  LocaleHeaderLayoutAdminLayoutAdminReviewsRouteImport.update({
    id: '/admin/reviews',
    path: '/admin/reviews',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRoute =
  LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRouteImport.update({
    id: '/admin/recently-claimed',
    path: '/admin/recently-claimed',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRoute =
  LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRouteImport.update({
    id: '/admin/pending-claims',
    path: '/admin/pending-claims',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminManagedListingsRoute =
  LocaleHeaderLayoutAdminLayoutAdminManagedListingsRouteImport.update({
    id: '/admin/managed-listings',
    path: '/admin/managed-listings',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRoute =
  LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRouteImport.update({
    id: '/admin/listing-product-accounts',
    path: '/admin/listing-product-accounts',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRoute =
  LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRouteImport.update({
    id: '/admin/home-page-hero',
    path: '/admin/home-page-hero',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRoute =
  LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRouteImport.update({
    id: '/admin/hero-candidates',
    path: '/admin/hero-candidates',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminHeroArtRoute =
  LocaleHeaderLayoutAdminLayoutAdminHeroArtRouteImport.update({
    id: '/admin/hero-art',
    path: '/admin/hero-art',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminAdminsRoute =
  LocaleHeaderLayoutAdminLayoutAdminAdminsRouteImport.update({
    id: '/admin/admins',
    path: '/admin/admins',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutAdminLayoutAdminAddListingRoute =
  LocaleHeaderLayoutAdminLayoutAdminAddListingRouteImport.update({
    id: '/admin/add-listing',
    path: '/admin/add-listing',
    getParentRoute: () => LocaleHeaderLayoutAdminLayoutRoute,
  } as any)
const LocaleHeaderLayoutProductsProductIdReviewsIndexRoute =
  LocaleHeaderLayoutProductsProductIdReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleHeaderLayoutProductsProductIdReviewsRoute,
  } as any)
const LocaleHeaderLayoutProductsProductIdReviewsWriteRoute =
  LocaleHeaderLayoutProductsProductIdReviewsWriteRouteImport.update({
    id: '/write',
    path: '/write',
    getParentRoute: () => LocaleHeaderLayoutProductsProductIdReviewsRoute,
  } as any)
const LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRoute =
  LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport.update({
    id: '/$reviewId/edit',
    path: '/$reviewId/edit',
    getParentRoute: () => LocaleHeaderLayoutProductsProductIdReviewsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleHeaderLayoutAdminLayoutRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/': typeof LocaleIndexRoute
  '/og/': typeof OgIndexRoute
  '/$locale/about': typeof LocaleHeaderLayoutAboutRoute
  '/$locale/home': typeof LocaleHeaderLayoutHomeRoute
  '/$locale/notifications': typeof LocaleHeaderLayoutNotificationsRoute
  '/$locale/search': typeof LocaleHeaderLayoutSearchRoute
  '/api/admin/hero-candidate-image': typeof ApiAdminHeroCandidateImageRoute
  '/$locale/apps/$tag': typeof LocaleHeaderLayoutAppsTagRoute
  '/$locale/apps/all': typeof LocaleHeaderLayoutAppsAllRoute
  '/$locale/apps/tags': typeof LocaleHeaderLayoutAppsTagsRoute
  '/$locale/categories/$categoryId': typeof LocaleHeaderLayoutCategoriesCategoryIdRoute
  '/$locale/dev/app-tags': typeof LocaleHeaderLayoutDevAppTagsRoute
  '/$locale/dev/categories': typeof LocaleHeaderLayoutDevCategoriesRoute
  '/$locale/product/claim': typeof LocaleHeaderLayoutProductClaimRoute
  '/$locale/products/create': typeof LocaleHeaderLayoutProductsCreateRoute
  '/$locale/profile/$actor': typeof LocaleHeaderLayoutProfileActorRoute
  '/$locale/protocol/$category': typeof LocaleHeaderLayoutProtocolCategoryRoute
  '/$locale/protocol/listings': typeof LocaleHeaderLayoutProtocolListingsRoute
  '/$locale/protocol/tags': typeof LocaleHeaderLayoutProtocolTagsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/$locale/admin/add-listing': typeof LocaleHeaderLayoutAdminLayoutAdminAddListingRoute
  '/$locale/admin/admins': typeof LocaleHeaderLayoutAdminLayoutAdminAdminsRoute
  '/$locale/admin/hero-art': typeof LocaleHeaderLayoutAdminLayoutAdminHeroArtRoute
  '/$locale/admin/hero-candidates': typeof LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRoute
  '/$locale/admin/home-page-hero': typeof LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/$locale/admin/listing-product-accounts': typeof LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRoute
  '/$locale/admin/managed-listings': typeof LocaleHeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/$locale/admin/pending-claims': typeof LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/$locale/admin/recently-claimed': typeof LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRoute
  '/$locale/admin/reviews': typeof LocaleHeaderLayoutAdminLayoutAdminReviewsRoute
  '/$locale/admin/unverified-listings': typeof LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/$locale/ecosystems/$app/all': typeof LocaleHeaderLayoutEcosystemsAppAllRoute
  '/$locale/products/$productId/edit': typeof LocaleHeaderLayoutProductsProductIdEditRoute
  '/$locale/products/$productId/mentions': typeof LocaleHeaderLayoutProductsProductIdMentionsRoute
  '/$locale/products/$productId/reviews': typeof LocaleHeaderLayoutProductsProductIdReviewsRouteWithChildren
  '/$locale/admin/': typeof LocaleHeaderLayoutAdminLayoutAdminIndexRoute
  '/$locale/ecosystems/$app/': typeof LocaleHeaderLayoutEcosystemsAppIndexRoute
  '/$locale/products/$productId/': typeof LocaleHeaderLayoutProductsProductIdIndexRoute
  '/$locale/products/$productId/reviews/write': typeof LocaleHeaderLayoutProductsProductIdReviewsWriteRoute
  '/$locale/products/$productId/reviews/': typeof LocaleHeaderLayoutProductsProductIdReviewsIndexRoute
  '/$locale/products/$productId/reviews/$reviewId/edit': typeof LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRoutesByTo {
  '/$locale': typeof LocaleHeaderLayoutAdminLayoutRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/og': typeof OgIndexRoute
  '/$locale/about': typeof LocaleHeaderLayoutAboutRoute
  '/$locale/home': typeof LocaleHeaderLayoutHomeRoute
  '/$locale/notifications': typeof LocaleHeaderLayoutNotificationsRoute
  '/$locale/search': typeof LocaleHeaderLayoutSearchRoute
  '/api/admin/hero-candidate-image': typeof ApiAdminHeroCandidateImageRoute
  '/$locale/apps/$tag': typeof LocaleHeaderLayoutAppsTagRoute
  '/$locale/apps/all': typeof LocaleHeaderLayoutAppsAllRoute
  '/$locale/apps/tags': typeof LocaleHeaderLayoutAppsTagsRoute
  '/$locale/categories/$categoryId': typeof LocaleHeaderLayoutCategoriesCategoryIdRoute
  '/$locale/dev/app-tags': typeof LocaleHeaderLayoutDevAppTagsRoute
  '/$locale/dev/categories': typeof LocaleHeaderLayoutDevCategoriesRoute
  '/$locale/product/claim': typeof LocaleHeaderLayoutProductClaimRoute
  '/$locale/products/create': typeof LocaleHeaderLayoutProductsCreateRoute
  '/$locale/profile/$actor': typeof LocaleHeaderLayoutProfileActorRoute
  '/$locale/protocol/$category': typeof LocaleHeaderLayoutProtocolCategoryRoute
  '/$locale/protocol/listings': typeof LocaleHeaderLayoutProtocolListingsRoute
  '/$locale/protocol/tags': typeof LocaleHeaderLayoutProtocolTagsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/$locale/admin/add-listing': typeof LocaleHeaderLayoutAdminLayoutAdminAddListingRoute
  '/$locale/admin/admins': typeof LocaleHeaderLayoutAdminLayoutAdminAdminsRoute
  '/$locale/admin/hero-art': typeof LocaleHeaderLayoutAdminLayoutAdminHeroArtRoute
  '/$locale/admin/hero-candidates': typeof LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRoute
  '/$locale/admin/home-page-hero': typeof LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/$locale/admin/listing-product-accounts': typeof LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRoute
  '/$locale/admin/managed-listings': typeof LocaleHeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/$locale/admin/pending-claims': typeof LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/$locale/admin/recently-claimed': typeof LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRoute
  '/$locale/admin/reviews': typeof LocaleHeaderLayoutAdminLayoutAdminReviewsRoute
  '/$locale/admin/unverified-listings': typeof LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/$locale/ecosystems/$app/all': typeof LocaleHeaderLayoutEcosystemsAppAllRoute
  '/$locale/products/$productId/edit': typeof LocaleHeaderLayoutProductsProductIdEditRoute
  '/$locale/products/$productId/mentions': typeof LocaleHeaderLayoutProductsProductIdMentionsRoute
  '/$locale/admin': typeof LocaleHeaderLayoutAdminLayoutAdminIndexRoute
  '/$locale/ecosystems/$app': typeof LocaleHeaderLayoutEcosystemsAppIndexRoute
  '/$locale/products/$productId': typeof LocaleHeaderLayoutProductsProductIdIndexRoute
  '/$locale/products/$productId/reviews/write': typeof LocaleHeaderLayoutProductsProductIdReviewsWriteRoute
  '/$locale/products/$productId/reviews': typeof LocaleHeaderLayoutProductsProductIdReviewsIndexRoute
  '/$locale/products/$productId/reviews/$reviewId/edit': typeof LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_header-layout': typeof LocaleHeaderLayoutRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/': typeof LocaleIndexRoute
  '/og/': typeof OgIndexRoute
  '/$locale/_header-layout/_admin-layout': typeof LocaleHeaderLayoutAdminLayoutRouteWithChildren
  '/$locale/_header-layout/about': typeof LocaleHeaderLayoutAboutRoute
  '/$locale/_header-layout/home': typeof LocaleHeaderLayoutHomeRoute
  '/$locale/_header-layout/notifications': typeof LocaleHeaderLayoutNotificationsRoute
  '/$locale/_header-layout/search': typeof LocaleHeaderLayoutSearchRoute
  '/api/admin/hero-candidate-image': typeof ApiAdminHeroCandidateImageRoute
  '/$locale/_header-layout/apps/$tag': typeof LocaleHeaderLayoutAppsTagRoute
  '/$locale/_header-layout/apps/all': typeof LocaleHeaderLayoutAppsAllRoute
  '/$locale/_header-layout/apps/tags': typeof LocaleHeaderLayoutAppsTagsRoute
  '/$locale/_header-layout/categories/$categoryId': typeof LocaleHeaderLayoutCategoriesCategoryIdRoute
  '/$locale/_header-layout/dev/app-tags': typeof LocaleHeaderLayoutDevAppTagsRoute
  '/$locale/_header-layout/dev/categories': typeof LocaleHeaderLayoutDevCategoriesRoute
  '/$locale/_header-layout/product/claim': typeof LocaleHeaderLayoutProductClaimRoute
  '/$locale/_header-layout/products/create': typeof LocaleHeaderLayoutProductsCreateRoute
  '/$locale/_header-layout/profile/$actor': typeof LocaleHeaderLayoutProfileActorRoute
  '/$locale/_header-layout/protocol/$category': typeof LocaleHeaderLayoutProtocolCategoryRoute
  '/$locale/_header-layout/protocol/listings': typeof LocaleHeaderLayoutProtocolListingsRoute
  '/$locale/_header-layout/protocol/tags': typeof LocaleHeaderLayoutProtocolTagsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/$locale/_header-layout/_admin-layout/admin/add-listing': typeof LocaleHeaderLayoutAdminLayoutAdminAddListingRoute
  '/$locale/_header-layout/_admin-layout/admin/admins': typeof LocaleHeaderLayoutAdminLayoutAdminAdminsRoute
  '/$locale/_header-layout/_admin-layout/admin/hero-art': typeof LocaleHeaderLayoutAdminLayoutAdminHeroArtRoute
  '/$locale/_header-layout/_admin-layout/admin/hero-candidates': typeof LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRoute
  '/$locale/_header-layout/_admin-layout/admin/home-page-hero': typeof LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/$locale/_header-layout/_admin-layout/admin/listing-product-accounts': typeof LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRoute
  '/$locale/_header-layout/_admin-layout/admin/managed-listings': typeof LocaleHeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/$locale/_header-layout/_admin-layout/admin/pending-claims': typeof LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/$locale/_header-layout/_admin-layout/admin/recently-claimed': typeof LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRoute
  '/$locale/_header-layout/_admin-layout/admin/reviews': typeof LocaleHeaderLayoutAdminLayoutAdminReviewsRoute
  '/$locale/_header-layout/_admin-layout/admin/unverified-listings': typeof LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/$locale/_header-layout/ecosystems/$app/all': typeof LocaleHeaderLayoutEcosystemsAppAllRoute
  '/$locale/_header-layout/products/$productId/edit': typeof LocaleHeaderLayoutProductsProductIdEditRoute
  '/$locale/_header-layout/products/$productId/mentions': typeof LocaleHeaderLayoutProductsProductIdMentionsRoute
  '/$locale/_header-layout/products/$productId/reviews': typeof LocaleHeaderLayoutProductsProductIdReviewsRouteWithChildren
  '/$locale/_header-layout/_admin-layout/admin/': typeof LocaleHeaderLayoutAdminLayoutAdminIndexRoute
  '/$locale/_header-layout/ecosystems/$app/': typeof LocaleHeaderLayoutEcosystemsAppIndexRoute
  '/$locale/_header-layout/products/$productId/': typeof LocaleHeaderLayoutProductsProductIdIndexRoute
  '/$locale/_header-layout/products/$productId/reviews/write': typeof LocaleHeaderLayoutProductsProductIdReviewsWriteRoute
  '/$locale/_header-layout/products/$productId/reviews/': typeof LocaleHeaderLayoutProductsProductIdReviewsIndexRoute
  '/$locale/_header-layout/products/$productId/reviews/$reviewId/edit': typeof LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/$locale/login'
    | '/$locale/'
    | '/og/'
    | '/$locale/about'
    | '/$locale/home'
    | '/$locale/notifications'
    | '/$locale/search'
    | '/api/admin/hero-candidate-image'
    | '/$locale/apps/$tag'
    | '/$locale/apps/all'
    | '/$locale/apps/tags'
    | '/$locale/categories/$categoryId'
    | '/$locale/dev/app-tags'
    | '/$locale/dev/categories'
    | '/$locale/product/claim'
    | '/$locale/products/create'
    | '/$locale/profile/$actor'
    | '/$locale/protocol/$category'
    | '/$locale/protocol/listings'
    | '/$locale/protocol/tags'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/$locale/admin/add-listing'
    | '/$locale/admin/admins'
    | '/$locale/admin/hero-art'
    | '/$locale/admin/hero-candidates'
    | '/$locale/admin/home-page-hero'
    | '/$locale/admin/listing-product-accounts'
    | '/$locale/admin/managed-listings'
    | '/$locale/admin/pending-claims'
    | '/$locale/admin/recently-claimed'
    | '/$locale/admin/reviews'
    | '/$locale/admin/unverified-listings'
    | '/$locale/ecosystems/$app/all'
    | '/$locale/products/$productId/edit'
    | '/$locale/products/$productId/mentions'
    | '/$locale/products/$productId/reviews'
    | '/$locale/admin/'
    | '/$locale/ecosystems/$app/'
    | '/$locale/products/$productId/'
    | '/$locale/products/$productId/reviews/write'
    | '/$locale/products/$productId/reviews/'
    | '/$locale/products/$productId/reviews/$reviewId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale'
    | '/$locale/login'
    | '/og'
    | '/$locale/about'
    | '/$locale/home'
    | '/$locale/notifications'
    | '/$locale/search'
    | '/api/admin/hero-candidate-image'
    | '/$locale/apps/$tag'
    | '/$locale/apps/all'
    | '/$locale/apps/tags'
    | '/$locale/categories/$categoryId'
    | '/$locale/dev/app-tags'
    | '/$locale/dev/categories'
    | '/$locale/product/claim'
    | '/$locale/products/create'
    | '/$locale/profile/$actor'
    | '/$locale/protocol/$category'
    | '/$locale/protocol/listings'
    | '/$locale/protocol/tags'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/$locale/admin/add-listing'
    | '/$locale/admin/admins'
    | '/$locale/admin/hero-art'
    | '/$locale/admin/hero-candidates'
    | '/$locale/admin/home-page-hero'
    | '/$locale/admin/listing-product-accounts'
    | '/$locale/admin/managed-listings'
    | '/$locale/admin/pending-claims'
    | '/$locale/admin/recently-claimed'
    | '/$locale/admin/reviews'
    | '/$locale/admin/unverified-listings'
    | '/$locale/ecosystems/$app/all'
    | '/$locale/products/$productId/edit'
    | '/$locale/products/$productId/mentions'
    | '/$locale/admin'
    | '/$locale/ecosystems/$app'
    | '/$locale/products/$productId'
    | '/$locale/products/$productId/reviews/write'
    | '/$locale/products/$productId/reviews'
    | '/$locale/products/$productId/reviews/$reviewId/edit'
  id:
    | '__root__'
    | '/$locale'
    | '/$locale/_header-layout'
    | '/$locale/login'
    | '/$locale/'
    | '/og/'
    | '/$locale/_header-layout/_admin-layout'
    | '/$locale/_header-layout/about'
    | '/$locale/_header-layout/home'
    | '/$locale/_header-layout/notifications'
    | '/$locale/_header-layout/search'
    | '/api/admin/hero-candidate-image'
    | '/$locale/_header-layout/apps/$tag'
    | '/$locale/_header-layout/apps/all'
    | '/$locale/_header-layout/apps/tags'
    | '/$locale/_header-layout/categories/$categoryId'
    | '/$locale/_header-layout/dev/app-tags'
    | '/$locale/_header-layout/dev/categories'
    | '/$locale/_header-layout/product/claim'
    | '/$locale/_header-layout/products/create'
    | '/$locale/_header-layout/profile/$actor'
    | '/$locale/_header-layout/protocol/$category'
    | '/$locale/_header-layout/protocol/listings'
    | '/$locale/_header-layout/protocol/tags'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/$locale/_header-layout/_admin-layout/admin/add-listing'
    | '/$locale/_header-layout/_admin-layout/admin/admins'
    | '/$locale/_header-layout/_admin-layout/admin/hero-art'
    | '/$locale/_header-layout/_admin-layout/admin/hero-candidates'
    | '/$locale/_header-layout/_admin-layout/admin/home-page-hero'
    | '/$locale/_header-layout/_admin-layout/admin/listing-product-accounts'
    | '/$locale/_header-layout/_admin-layout/admin/managed-listings'
    | '/$locale/_header-layout/_admin-layout/admin/pending-claims'
    | '/$locale/_header-layout/_admin-layout/admin/recently-claimed'
    | '/$locale/_header-layout/_admin-layout/admin/reviews'
    | '/$locale/_header-layout/_admin-layout/admin/unverified-listings'
    | '/$locale/_header-layout/ecosystems/$app/all'
    | '/$locale/_header-layout/products/$productId/edit'
    | '/$locale/_header-layout/products/$productId/mentions'
    | '/$locale/_header-layout/products/$productId/reviews'
    | '/$locale/_header-layout/_admin-layout/admin/'
    | '/$locale/_header-layout/ecosystems/$app/'
    | '/$locale/_header-layout/products/$productId/'
    | '/$locale/_header-layout/products/$productId/reviews/write'
    | '/$locale/_header-layout/products/$productId/reviews/'
    | '/$locale/_header-layout/products/$productId/reviews/$reviewId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
  OgIndexRoute: typeof OgIndexRoute
  ApiAdminHeroCandidateImageRoute: typeof ApiAdminHeroCandidateImageRoute
  ApiAuthAtprotoAuthorizeRoute: typeof ApiAuthAtprotoAuthorizeRoute
  ApiAuthAtprotoCallbackRoute: typeof ApiAuthAtprotoCallbackRoute
  ApiAuthAtprotoJwksDotjsonRoute: typeof ApiAuthAtprotoJwksDotjsonRoute
  ApiAuthAtprotoMetadataDotjsonRoute: typeof ApiAuthAtprotoMetadataDotjsonRoute
  ApiAuthAtprotoSignupRoute: typeof ApiAuthAtprotoSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/': {
      id: '/og/'
      path: '/og'
      fullPath: '/og/'
      preLoaderRoute: typeof OgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_header-layout': {
      id: '/$locale/_header-layout'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleHeaderLayoutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/admin/hero-candidate-image': {
      id: '/api/admin/hero-candidate-image'
      path: '/api/admin/hero-candidate-image'
      fullPath: '/api/admin/hero-candidate-image'
      preLoaderRoute: typeof ApiAdminHeroCandidateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_header-layout/search': {
      id: '/$locale/_header-layout/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleHeaderLayoutSearchRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/notifications': {
      id: '/$locale/_header-layout/notifications'
      path: '/notifications'
      fullPath: '/$locale/notifications'
      preLoaderRoute: typeof LocaleHeaderLayoutNotificationsRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/home': {
      id: '/$locale/_header-layout/home'
      path: '/home'
      fullPath: '/$locale/home'
      preLoaderRoute: typeof LocaleHeaderLayoutHomeRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/about': {
      id: '/$locale/_header-layout/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleHeaderLayoutAboutRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout': {
      id: '/$locale/_header-layout/_admin-layout'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/api/auth/atproto/signup': {
      id: '/api/auth/atproto/signup'
      path: '/api/auth/atproto/signup'
      fullPath: '/api/auth/atproto/signup'
      preLoaderRoute: typeof ApiAuthAtprotoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/metadata.json': {
      id: '/api/auth/atproto/metadata.json'
      path: '/api/auth/atproto/metadata.json'
      fullPath: '/api/auth/atproto/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/jwks.json': {
      id: '/api/auth/atproto/jwks.json'
      path: '/api/auth/atproto/jwks.json'
      fullPath: '/api/auth/atproto/jwks.json'
      preLoaderRoute: typeof ApiAuthAtprotoJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/callback': {
      id: '/api/auth/atproto/callback'
      path: '/api/auth/atproto/callback'
      fullPath: '/api/auth/atproto/callback'
      preLoaderRoute: typeof ApiAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/authorize': {
      id: '/api/auth/atproto/authorize'
      path: '/api/auth/atproto/authorize'
      fullPath: '/api/auth/atproto/authorize'
      preLoaderRoute: typeof ApiAuthAtprotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_header-layout/protocol/tags': {
      id: '/$locale/_header-layout/protocol/tags'
      path: '/protocol/tags'
      fullPath: '/$locale/protocol/tags'
      preLoaderRoute: typeof LocaleHeaderLayoutProtocolTagsRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/protocol/listings': {
      id: '/$locale/_header-layout/protocol/listings'
      path: '/protocol/listings'
      fullPath: '/$locale/protocol/listings'
      preLoaderRoute: typeof LocaleHeaderLayoutProtocolListingsRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/protocol/$category': {
      id: '/$locale/_header-layout/protocol/$category'
      path: '/protocol/$category'
      fullPath: '/$locale/protocol/$category'
      preLoaderRoute: typeof LocaleHeaderLayoutProtocolCategoryRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/profile/$actor': {
      id: '/$locale/_header-layout/profile/$actor'
      path: '/profile/$actor'
      fullPath: '/$locale/profile/$actor'
      preLoaderRoute: typeof LocaleHeaderLayoutProfileActorRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/products/create': {
      id: '/$locale/_header-layout/products/create'
      path: '/products/create'
      fullPath: '/$locale/products/create'
      preLoaderRoute: typeof LocaleHeaderLayoutProductsCreateRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/product/claim': {
      id: '/$locale/_header-layout/product/claim'
      path: '/product/claim'
      fullPath: '/$locale/product/claim'
      preLoaderRoute: typeof LocaleHeaderLayoutProductClaimRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/dev/categories': {
      id: '/$locale/_header-layout/dev/categories'
      path: '/dev/categories'
      fullPath: '/$locale/dev/categories'
      preLoaderRoute: typeof LocaleHeaderLayoutDevCategoriesRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/dev/app-tags': {
      id: '/$locale/_header-layout/dev/app-tags'
      path: '/dev/app-tags'
      fullPath: '/$locale/dev/app-tags'
      preLoaderRoute: typeof LocaleHeaderLayoutDevAppTagsRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/categories/$categoryId': {
      id: '/$locale/_header-layout/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/$locale/categories/$categoryId'
      preLoaderRoute: typeof LocaleHeaderLayoutCategoriesCategoryIdRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/apps/tags': {
      id: '/$locale/_header-layout/apps/tags'
      path: '/apps/tags'
      fullPath: '/$locale/apps/tags'
      preLoaderRoute: typeof LocaleHeaderLayoutAppsTagsRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/apps/all': {
      id: '/$locale/_header-layout/apps/all'
      path: '/apps/all'
      fullPath: '/$locale/apps/all'
      preLoaderRoute: typeof LocaleHeaderLayoutAppsAllRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/apps/$tag': {
      id: '/$locale/_header-layout/apps/$tag'
      path: '/apps/$tag'
      fullPath: '/$locale/apps/$tag'
      preLoaderRoute: typeof LocaleHeaderLayoutAppsTagRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/products/$productId/': {
      id: '/$locale/_header-layout/products/$productId/'
      path: '/products/$productId'
      fullPath: '/$locale/products/$productId/'
      preLoaderRoute: typeof LocaleHeaderLayoutProductsProductIdIndexRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/ecosystems/$app/': {
      id: '/$locale/_header-layout/ecosystems/$app/'
      path: '/ecosystems/$app'
      fullPath: '/$locale/ecosystems/$app/'
      preLoaderRoute: typeof LocaleHeaderLayoutEcosystemsAppIndexRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/': {
      id: '/$locale/_header-layout/_admin-layout/admin/'
      path: '/admin'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminIndexRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/products/$productId/reviews': {
      id: '/$locale/_header-layout/products/$productId/reviews'
      path: '/products/$productId/reviews'
      fullPath: '/$locale/products/$productId/reviews'
      preLoaderRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/products/$productId/mentions': {
      id: '/$locale/_header-layout/products/$productId/mentions'
      path: '/products/$productId/mentions'
      fullPath: '/$locale/products/$productId/mentions'
      preLoaderRoute: typeof LocaleHeaderLayoutProductsProductIdMentionsRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/products/$productId/edit': {
      id: '/$locale/_header-layout/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/$locale/products/$productId/edit'
      preLoaderRoute: typeof LocaleHeaderLayoutProductsProductIdEditRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/ecosystems/$app/all': {
      id: '/$locale/_header-layout/ecosystems/$app/all'
      path: '/ecosystems/$app/all'
      fullPath: '/$locale/ecosystems/$app/all'
      preLoaderRoute: typeof LocaleHeaderLayoutEcosystemsAppAllRouteImport
      parentRoute: typeof LocaleHeaderLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/unverified-listings': {
      id: '/$locale/_header-layout/_admin-layout/admin/unverified-listings'
      path: '/admin/unverified-listings'
      fullPath: '/$locale/admin/unverified-listings'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/reviews': {
      id: '/$locale/_header-layout/_admin-layout/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/$locale/admin/reviews'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminReviewsRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/recently-claimed': {
      id: '/$locale/_header-layout/_admin-layout/admin/recently-claimed'
      path: '/admin/recently-claimed'
      fullPath: '/$locale/admin/recently-claimed'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/pending-claims': {
      id: '/$locale/_header-layout/_admin-layout/admin/pending-claims'
      path: '/admin/pending-claims'
      fullPath: '/$locale/admin/pending-claims'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/managed-listings': {
      id: '/$locale/_header-layout/_admin-layout/admin/managed-listings'
      path: '/admin/managed-listings'
      fullPath: '/$locale/admin/managed-listings'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminManagedListingsRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/listing-product-accounts': {
      id: '/$locale/_header-layout/_admin-layout/admin/listing-product-accounts'
      path: '/admin/listing-product-accounts'
      fullPath: '/$locale/admin/listing-product-accounts'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/home-page-hero': {
      id: '/$locale/_header-layout/_admin-layout/admin/home-page-hero'
      path: '/admin/home-page-hero'
      fullPath: '/$locale/admin/home-page-hero'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/hero-candidates': {
      id: '/$locale/_header-layout/_admin-layout/admin/hero-candidates'
      path: '/admin/hero-candidates'
      fullPath: '/$locale/admin/hero-candidates'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/hero-art': {
      id: '/$locale/_header-layout/_admin-layout/admin/hero-art'
      path: '/admin/hero-art'
      fullPath: '/$locale/admin/hero-art'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminHeroArtRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/admins': {
      id: '/$locale/_header-layout/_admin-layout/admin/admins'
      path: '/admin/admins'
      fullPath: '/$locale/admin/admins'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminAdminsRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/_admin-layout/admin/add-listing': {
      id: '/$locale/_header-layout/_admin-layout/admin/add-listing'
      path: '/admin/add-listing'
      fullPath: '/$locale/admin/add-listing'
      preLoaderRoute: typeof LocaleHeaderLayoutAdminLayoutAdminAddListingRouteImport
      parentRoute: typeof LocaleHeaderLayoutAdminLayoutRoute
    }
    '/$locale/_header-layout/products/$productId/reviews/': {
      id: '/$locale/_header-layout/products/$productId/reviews/'
      path: '/'
      fullPath: '/$locale/products/$productId/reviews/'
      preLoaderRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsIndexRouteImport
      parentRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsRoute
    }
    '/$locale/_header-layout/products/$productId/reviews/write': {
      id: '/$locale/_header-layout/products/$productId/reviews/write'
      path: '/write'
      fullPath: '/$locale/products/$productId/reviews/write'
      preLoaderRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsWriteRouteImport
      parentRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsRoute
    }
    '/$locale/_header-layout/products/$productId/reviews/$reviewId/edit': {
      id: '/$locale/_header-layout/products/$productId/reviews/$reviewId/edit'
      path: '/$reviewId/edit'
      fullPath: '/$locale/products/$productId/reviews/$reviewId/edit'
      preLoaderRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport
      parentRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsRoute
    }
  }
}

interface LocaleHeaderLayoutAdminLayoutRouteChildren {
  LocaleHeaderLayoutAdminLayoutAdminAddListingRoute: typeof LocaleHeaderLayoutAdminLayoutAdminAddListingRoute
  LocaleHeaderLayoutAdminLayoutAdminAdminsRoute: typeof LocaleHeaderLayoutAdminLayoutAdminAdminsRoute
  LocaleHeaderLayoutAdminLayoutAdminHeroArtRoute: typeof LocaleHeaderLayoutAdminLayoutAdminHeroArtRoute
  LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRoute: typeof LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRoute
  LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRoute: typeof LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRoute
  LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRoute: typeof LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRoute
  LocaleHeaderLayoutAdminLayoutAdminManagedListingsRoute: typeof LocaleHeaderLayoutAdminLayoutAdminManagedListingsRoute
  LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRoute: typeof LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRoute
  LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRoute: typeof LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRoute
  LocaleHeaderLayoutAdminLayoutAdminReviewsRoute: typeof LocaleHeaderLayoutAdminLayoutAdminReviewsRoute
  LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRoute: typeof LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  LocaleHeaderLayoutAdminLayoutAdminIndexRoute: typeof LocaleHeaderLayoutAdminLayoutAdminIndexRoute
}

const LocaleHeaderLayoutAdminLayoutRouteChildren: LocaleHeaderLayoutAdminLayoutRouteChildren =
  {
    LocaleHeaderLayoutAdminLayoutAdminAddListingRoute:
      LocaleHeaderLayoutAdminLayoutAdminAddListingRoute,
    LocaleHeaderLayoutAdminLayoutAdminAdminsRoute:
      LocaleHeaderLayoutAdminLayoutAdminAdminsRoute,
    LocaleHeaderLayoutAdminLayoutAdminHeroArtRoute:
      LocaleHeaderLayoutAdminLayoutAdminHeroArtRoute,
    LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRoute:
      LocaleHeaderLayoutAdminLayoutAdminHeroCandidatesRoute,
    LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRoute:
      LocaleHeaderLayoutAdminLayoutAdminHomePageHeroRoute,
    LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRoute:
      LocaleHeaderLayoutAdminLayoutAdminListingProductAccountsRoute,
    LocaleHeaderLayoutAdminLayoutAdminManagedListingsRoute:
      LocaleHeaderLayoutAdminLayoutAdminManagedListingsRoute,
    LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRoute:
      LocaleHeaderLayoutAdminLayoutAdminPendingClaimsRoute,
    LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRoute:
      LocaleHeaderLayoutAdminLayoutAdminRecentlyClaimedRoute,
    LocaleHeaderLayoutAdminLayoutAdminReviewsRoute:
      LocaleHeaderLayoutAdminLayoutAdminReviewsRoute,
    LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRoute:
      LocaleHeaderLayoutAdminLayoutAdminUnverifiedListingsRoute,
    LocaleHeaderLayoutAdminLayoutAdminIndexRoute:
      LocaleHeaderLayoutAdminLayoutAdminIndexRoute,
  }

const LocaleHeaderLayoutAdminLayoutRouteWithChildren =
  LocaleHeaderLayoutAdminLayoutRoute._addFileChildren(
    LocaleHeaderLayoutAdminLayoutRouteChildren,
  )

interface LocaleHeaderLayoutProductsProductIdReviewsRouteChildren {
  LocaleHeaderLayoutProductsProductIdReviewsWriteRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsWriteRoute
  LocaleHeaderLayoutProductsProductIdReviewsIndexRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsIndexRoute
  LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}

const LocaleHeaderLayoutProductsProductIdReviewsRouteChildren: LocaleHeaderLayoutProductsProductIdReviewsRouteChildren =
  {
    LocaleHeaderLayoutProductsProductIdReviewsWriteRoute:
      LocaleHeaderLayoutProductsProductIdReviewsWriteRoute,
    LocaleHeaderLayoutProductsProductIdReviewsIndexRoute:
      LocaleHeaderLayoutProductsProductIdReviewsIndexRoute,
    LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRoute:
      LocaleHeaderLayoutProductsProductIdReviewsReviewIdEditRoute,
  }

const LocaleHeaderLayoutProductsProductIdReviewsRouteWithChildren =
  LocaleHeaderLayoutProductsProductIdReviewsRoute._addFileChildren(
    LocaleHeaderLayoutProductsProductIdReviewsRouteChildren,
  )

interface LocaleHeaderLayoutRouteChildren {
  LocaleHeaderLayoutAdminLayoutRoute: typeof LocaleHeaderLayoutAdminLayoutRouteWithChildren
  LocaleHeaderLayoutAboutRoute: typeof LocaleHeaderLayoutAboutRoute
  LocaleHeaderLayoutHomeRoute: typeof LocaleHeaderLayoutHomeRoute
  LocaleHeaderLayoutNotificationsRoute: typeof LocaleHeaderLayoutNotificationsRoute
  LocaleHeaderLayoutSearchRoute: typeof LocaleHeaderLayoutSearchRoute
  LocaleHeaderLayoutAppsTagRoute: typeof LocaleHeaderLayoutAppsTagRoute
  LocaleHeaderLayoutAppsAllRoute: typeof LocaleHeaderLayoutAppsAllRoute
  LocaleHeaderLayoutAppsTagsRoute: typeof LocaleHeaderLayoutAppsTagsRoute
  LocaleHeaderLayoutCategoriesCategoryIdRoute: typeof LocaleHeaderLayoutCategoriesCategoryIdRoute
  LocaleHeaderLayoutDevAppTagsRoute: typeof LocaleHeaderLayoutDevAppTagsRoute
  LocaleHeaderLayoutDevCategoriesRoute: typeof LocaleHeaderLayoutDevCategoriesRoute
  LocaleHeaderLayoutProductClaimRoute: typeof LocaleHeaderLayoutProductClaimRoute
  LocaleHeaderLayoutProductsCreateRoute: typeof LocaleHeaderLayoutProductsCreateRoute
  LocaleHeaderLayoutProfileActorRoute: typeof LocaleHeaderLayoutProfileActorRoute
  LocaleHeaderLayoutProtocolCategoryRoute: typeof LocaleHeaderLayoutProtocolCategoryRoute
  LocaleHeaderLayoutProtocolListingsRoute: typeof LocaleHeaderLayoutProtocolListingsRoute
  LocaleHeaderLayoutProtocolTagsRoute: typeof LocaleHeaderLayoutProtocolTagsRoute
  LocaleHeaderLayoutEcosystemsAppAllRoute: typeof LocaleHeaderLayoutEcosystemsAppAllRoute
  LocaleHeaderLayoutProductsProductIdEditRoute: typeof LocaleHeaderLayoutProductsProductIdEditRoute
  LocaleHeaderLayoutProductsProductIdMentionsRoute: typeof LocaleHeaderLayoutProductsProductIdMentionsRoute
  LocaleHeaderLayoutProductsProductIdReviewsRoute: typeof LocaleHeaderLayoutProductsProductIdReviewsRouteWithChildren
  LocaleHeaderLayoutEcosystemsAppIndexRoute: typeof LocaleHeaderLayoutEcosystemsAppIndexRoute
  LocaleHeaderLayoutProductsProductIdIndexRoute: typeof LocaleHeaderLayoutProductsProductIdIndexRoute
}

const LocaleHeaderLayoutRouteChildren: LocaleHeaderLayoutRouteChildren = {
  LocaleHeaderLayoutAdminLayoutRoute:
    LocaleHeaderLayoutAdminLayoutRouteWithChildren,
  LocaleHeaderLayoutAboutRoute: LocaleHeaderLayoutAboutRoute,
  LocaleHeaderLayoutHomeRoute: LocaleHeaderLayoutHomeRoute,
  LocaleHeaderLayoutNotificationsRoute: LocaleHeaderLayoutNotificationsRoute,
  LocaleHeaderLayoutSearchRoute: LocaleHeaderLayoutSearchRoute,
  LocaleHeaderLayoutAppsTagRoute: LocaleHeaderLayoutAppsTagRoute,
  LocaleHeaderLayoutAppsAllRoute: LocaleHeaderLayoutAppsAllRoute,
  LocaleHeaderLayoutAppsTagsRoute: LocaleHeaderLayoutAppsTagsRoute,
  LocaleHeaderLayoutCategoriesCategoryIdRoute:
    LocaleHeaderLayoutCategoriesCategoryIdRoute,
  LocaleHeaderLayoutDevAppTagsRoute: LocaleHeaderLayoutDevAppTagsRoute,
  LocaleHeaderLayoutDevCategoriesRoute: LocaleHeaderLayoutDevCategoriesRoute,
  LocaleHeaderLayoutProductClaimRoute: LocaleHeaderLayoutProductClaimRoute,
  LocaleHeaderLayoutProductsCreateRoute: LocaleHeaderLayoutProductsCreateRoute,
  LocaleHeaderLayoutProfileActorRoute: LocaleHeaderLayoutProfileActorRoute,
  LocaleHeaderLayoutProtocolCategoryRoute:
    LocaleHeaderLayoutProtocolCategoryRoute,
  LocaleHeaderLayoutProtocolListingsRoute:
    LocaleHeaderLayoutProtocolListingsRoute,
  LocaleHeaderLayoutProtocolTagsRoute: LocaleHeaderLayoutProtocolTagsRoute,
  LocaleHeaderLayoutEcosystemsAppAllRoute:
    LocaleHeaderLayoutEcosystemsAppAllRoute,
  LocaleHeaderLayoutProductsProductIdEditRoute:
    LocaleHeaderLayoutProductsProductIdEditRoute,
  LocaleHeaderLayoutProductsProductIdMentionsRoute:
    LocaleHeaderLayoutProductsProductIdMentionsRoute,
  LocaleHeaderLayoutProductsProductIdReviewsRoute:
    LocaleHeaderLayoutProductsProductIdReviewsRouteWithChildren,
  LocaleHeaderLayoutEcosystemsAppIndexRoute:
    LocaleHeaderLayoutEcosystemsAppIndexRoute,
  LocaleHeaderLayoutProductsProductIdIndexRoute:
    LocaleHeaderLayoutProductsProductIdIndexRoute,
}

const LocaleHeaderLayoutRouteWithChildren =
  LocaleHeaderLayoutRoute._addFileChildren(LocaleHeaderLayoutRouteChildren)

interface LocaleRouteChildren {
  LocaleHeaderLayoutRoute: typeof LocaleHeaderLayoutRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleHeaderLayoutRoute: LocaleHeaderLayoutRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
  OgIndexRoute: OgIndexRoute,
  ApiAdminHeroCandidateImageRoute: ApiAdminHeroCandidateImageRoute,
  ApiAuthAtprotoAuthorizeRoute: ApiAuthAtprotoAuthorizeRoute,
  ApiAuthAtprotoCallbackRoute: ApiAuthAtprotoCallbackRoute,
  ApiAuthAtprotoJwksDotjsonRoute: ApiAuthAtprotoJwksDotjsonRoute,
  ApiAuthAtprotoMetadataDotjsonRoute: ApiAuthAtprotoMetadataDotjsonRoute,
  ApiAuthAtprotoSignupRoute: ApiAuthAtprotoSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
